name: tasksmanager-backend-api deployment

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev ]
    paths:
    - 'TasksTracker.TasksManager.Backend.Api/**'
    - '.github/workflows/build-deploy-backend-api.yaml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: taskstrackeracrvkp.azurecr.io
          username: ${{ secrets.TASKSMANAGER_REGISTRY_USERNAME }}
          password: ${{ secrets.TASKSMANAGER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: taskstrackeracrvkp.azurecr.io/tasksmanager-backend-api:${{ github.sha }} , taskstrackeracrvkp.azurecr.io/tasksmanager-backend-api:latest
          file: TasksTracker.TasksManager.Backend.Api/Dockerfile
          context: ./.


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TASKSMANAGER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n mycontainerapp -g MyContainerAppRG --server taskstrackeracrvkp.azurecr.io --username  ${{ secrets.TASKSMANAGER_REGISTRY_USERNAME }} --password ${{ secrets.TASKSMANAGER_REGISTRY_PASSWORD }}
            az containerapp update -n mycontainerapp -g MyContainerAppRG --image taskstrackeracrvkp.azurecr.io/tasksmanager-backend-api:${{ github.sha }}
